version: "3"

networks:
  frontend:
    external: true
  app:
    driver: bridge
    internal: false
  pretix:
    driver: bridge
    internal: false

services:
  mariadb:
    image: itkdev/mariadb:latest
    networks:
      - app
    ports:
      - '3306'
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=db
      - MYSQL_PASSWORD=db
      - MYSQL_DATABASE=db
      #- ENCRYPT=1 # Uncomment to enable database encryptionn.

  phpfpm:
    image: itkdev/php7.2-fpm:latest
    container_name: ${COMPOSE_PROJECT_NAME}-phpfpm
    networks:
      - app
    environment:
      - PHP_XDEBUG=${PHP_XDEBUG:-0}
      - PHP_XDEBUG_REMOTE_AUTOSTART=${PHP_XDEBUG_REMOTE_AUTOSTART:-0}
      - PHP_XDEBUG_REMOTE_HOST=${PHP_XDEBUG_REMOTE_HOST:-0.0.0.0}
      - PHP_XDEBUG_REMOTE_CONNECT_BACK=${PHP_XDEBUG_REMOTE_CONNECT_BACK:-0}
      - PHP_MAX_EXECUTION_TIME=30
      - PHP_MEMORY_LIMIT=256M
      # - PHP_MAIL=1 # Uncomment to enable mailhog.
      - DOCKER_HOST_DOMAIN=${COMPOSE_DOMAIN}
    depends_on:
      - mariadb
    # volumes:
    #   - .:/app:delegated

  nginx:
    image: nginx:latest
    container_name: ${COMPOSE_PROJECT_NAME}-nginx
    networks:
      - app
      - frontend
    depends_on:
      - phpfpm
      - memcached
    ports:
      - '80'
    volumes:
      - ${PWD}/.docker/vhost.conf:/etc/nginx/conf.d/default.conf:ro
      # - ./:/app:delegated
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=frontend"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${COMPOSE_DOMAIN}`)"

  memcached:
    image: 'memcached:latest'
    networks:
      - app
    ports:
      - '11211'
    environment:
      - MEMCACHED_CACHE_SIZE=64

  mailhog:
    image: mailhog/mailhog
    networks:
      - app
    ports:
      - "1025"
      - "8025"

  pretix:
    image: pretix/standalone:stable
    networks:
      - app
      - pretix
      - frontend
    depends_on:
      - pretix_database
      - pretix_redis
      - mailhog
    ports:
      - '80'
    volumes:
      - ${PWD}/.docker/pretix/etc/pretix.cfg:/etc/pretix/pretix.cfg

    # Let the pretix container be accessible both internally and externally on the same domain.
    container_name: pretix.${COMPOSE_DOMAIN}
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=frontend"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}_pretix.rule=Host(`pretix.${COMPOSE_DOMAIN}`)"

  pretix_database:
    image: mariadb:10.3
    networks:
      - pretix
    ports:
      - '3306'
    volumes:
      - .docker/pretix/dumps:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: pretix
      MYSQL_PASSWORD: pretix
      MYSQL_DATABASE: pretix

  pretix_redis:
    image: redis:latest
    networks:
      - pretix
    ports:
      - "6379"
