<?php

/**
 * @file
 * Contains hoeringsportal_project_timeline.module.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_theme().
 */
function hoeringsportal_project_timeline_theme() {
  return [
    'hoeringsportal_project_timeline' => [
      'template' => 'hoeringsportal-project-timeline',
      'variables' => [
        'items' => [],
        'legend_items' => [],
        'default_view' => 'vertical',
      ],
    ],
    'project_timeline_card' => [
      'template' => 'project-timeline-card',
      'variables' => [
        'item' => [],
      ],
    ],
    'project_timeline_mini_nav' => [
      'template' => 'project-timeline-mini-nav',
      'variables' => [
        'items' => [],
      ],
    ],
    'project_timeline_legend' => [
      'template' => 'project-timeline-legend',
      'variables' => [
        'items' => [],
      ],
    ],
  ];
}

/**
 * Implements hook_form_FORMID_alter().
 */
function hoeringsportal_project_timeline_form_node_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ('node_project_form' === $form_id || 'node_project_edit_form' === $form_id) {
    $form['#attached']['library'][] = 'hoeringsportal_project_timeline/project_timeline_backend';
  }
}
