<?php

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\hoeringsportal_activity\Helper\ActivityHelper;

/**
 * Implements hook_theme().
 */
function hoeringsportal_activity_theme($existing, $type, $theme, $path) : array {
  return [
    'hoeringsportal_activity_add_activity' => [
      'variables' => [
        'entities' => NULL,
        'module_path' => $path,
      ],
    ],
  ];
}

function hoeringsportal_activity_entity_presave(EntityInterface $entity) {
  Drupal::service(ActivityHelper::class)->coursePresave($entity);
}

function hoeringsportal_activity_form_node_course_form_alter(&$form, FormStateInterface $form_state) {
  Drupal::service(ActivityHelper::class)->activityFormAlter($form, $form_state);
}

function hoeringsportal_activity_form_node_course_edit_form_alter(&$form, FormStateInterface $form_state) {
  Drupal::service(ActivityHelper::class)->activityFormAlter($form, $form_state);
}

function hoeringsportal_activity_form_node_public_meeting_form_alter(&$form, FormStateInterface $form_state) {
  Drupal::service(ActivityHelper::class)->activityFormAlter($form, $form_state);
}

function hoeringsportal_activity_form_node_public_meeting_edit_form_alter(&$form, FormStateInterface $form_state) {
  Drupal::service(ActivityHelper::class)->activityFormAlter($form, $form_state);
}
