when:
  - branch: release/*
    event: push

skip_clone: true

labels:
  zone: CLOUD

steps:
  - name: Run stg site update
    image: itkdev/ansible-plugin:1
    pull: true
    settings:
      id:
        from_secret: id
      secret:
        from_secret: secret
      host:
        from_secret: stg_host
      path:
        from_secret: stg_path
      user:
        from_secret: user
      actions:
        - git reset --hard
        - git fetch origin ${CI_COMMIT_BRANCH}
        - git checkout ${CI_COMMIT_BRANCH}
        - git pull
        # Apply patch needed for testing MitID sign-in (see patch for details).
        - git apply patches/development/mitid-test-cpr-hack.patch
        - itkdev-docker-compose-server up -d --force-recreate --remove-orphans
        - itkdev-docker-compose-server exec phpfpm composer install --no-dev -o --classmap-authoritative
        - itkdev-docker-compose-server exec phpfpm composer clear-cache
        - itkdev-docker-compose-server exec phpfpm vendor/bin/drush --yes cache:rebuild
        - itkdev-docker-compose-server exec phpfpm vendor/bin/drush --yes deploy
        # Fixes issue with 'Drupal\mysql\Driver\Database\mysql\Connection' not found
        - itkdev-docker-compose-server exec phpfpm composer dump-autoload
        - docker compose run --rm node npm --prefix web/themes/custom/hoeringsportal install
        - docker compose run --rm node npm --prefix web/themes/custom/hoeringsportal run build
        - docker compose run --rm node rm -rf web/themes/custom/hoeringsportal/node_modules
        - itkdev-docker-compose-server exec phpfpm vendor/bin/drush --yes cache:rebuild
