name: Hoeringsportal admin
type: module
description: 'Provides config settings and admin interface for hoeringsportalen'
core_version_requirement: ^8.8 || ^9
package: Hoeringsportal
dependencies:
  - drupal:itk_admin
